name: Test Secret

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar secret
        env:
          HOLA: ${{ secrets.HOLA }}
        run: |
          echo "El secret existe"
          echo "$HOLA"